version: "3.9"

services:
  odoo:
    build: ./box
    ports:
      - "8069:8069"
    volumes:
      - ./:/opt/odoo
      - odoo_data:/root/.local/share/Odoo
    user: root
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8069" ]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - postgres
      # - nginx
    restart: unless-stopped
    tty: true
    command: bash -c "python3 /opt/odoo/odoo/odoo-bin --addons-path=/opt/odoo/customized/demo_course,/opt/odoo/odoo/addons -c /opt/odoo/odoo.conf && tail -f /dev/null"

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    tty: true

volumes:
  odoo_data:
  postgres_data:
